### ISSUE TITLE
Next steps and to dos

### ISSUE THREAD

**Issue by FelixMay** [FelixMay/FragFrame_1#1]
# ToDo's Felix
- [x] Set up GitHub Repository and add me/you as collaborator
 
- [x] Data frame containing studies, fragment ranks (continuous = 9999), biodiversity metrics, exclude matrix entities, pool samples within the same fragment (those can be used to test changes in spatial aggregation)

- [x] Data table with meta-data

- [x] Calculate standardized N, take into account different sampling efforts for calculation of N

# ToDo's Katharina
 - [x] Calculate effect size Fishers’ z and variance for each study

 - [x] Setting up analyses on effect sizes for BDmetrics separately

 - [ ] Think about a multivariate analysis including correlation of BDmetrics

- [x] Calculate log-ratio effect sizes for studies with just two fragment sizes (continuous vs. fragmented)

**Comment by FelixMay** [comment]
@KatharinaGerstner : Das Skript zum laden der Pakete und zum Setzen der Ordner ist praktisch. Aber lässt sich irgendwie verhindern, dass MoBspatial und iNext immer neu von GitHUb installiert werden?
