### ISSUE TITLE
Improve reproducibility of the results and analysis

### ISSUE THREAD

**Issue by FelixMay** [FelixMay/FragFrame_1#7]
# ToDo's for all

- [x] Only specify absolute paths once
- [x] Remove all other absolute paths
- [x] save intermediate and main results in GitHub repo and NOT in the DropBox

# ToDo for Felix

- [x] adjust preprocessing files (which do use data from DropBox accordingly)
- [x] check if iNEXT is still needed and helper function in 0_-init script
- [x] Finalize README
- [x] archive on ZENODO

**Comment by FelixMay** [comment]
@sablowes @AlbanSagouis: I am not sure what the best way of using packages is in the repo. Should we load (and install) them all in the first initial R script as currently or only load them in the scripts where they are needed?

**Comment by sablowes** [comment]
Either is fine for me. I kinda like the process of loading them in the initial script (once I got used to remembering to run it). I know there are some (e.g., ggridges) that need to be added if we go that way.

You decide!

**Comment by AlbanSagouis** [comment]
I load only `mobsim` so it is very limited and already mentioned in your own scripts.

**Comment by FelixMay** [comment]
Hi @sablowes and @AlbanSagouis,
alright, then please add all necessary packages to 0_init_dirs_load_packages.R and remove all library(), require() or install.package() calls from your R scripts.

Alban, maybe for your script the challenge will be that you used your latest mobsim version from GiHub, while for other users it will be much more easy to use the CRAN version of mobsim. Does that cause problems? Of course, the best would be to release an updated version on CRAN, but this might include some effort. So from my perspective it would be best if your script just uses the CRAN version. Another option is to add a call to install_github() into 0_init_dirs_load_packages.R so that the latest version is installed. What do you think?

**Comment by FelixMay** [comment]
Hi @sablowes and @AlbanSagouis,

I hope I did all necessary changes in "my" main files 0_init_dirs_load_packages.R and 1_analysis_get_biodiv_new.R. Currently R is running and creating the results again and saves them into the intermediate_results folder. I already pushed the first part onto GitHub.

Do you agree to the adjusted file structure?

So from my side you can jump into adjusting your files now. Let me know when there are any question.

@sablowes: what is your plan to deal with computations you did on EVE? Maybe just comments so that readers get an idea, which analysis can be repeated on y laptop and where they rather load intermediate results from files, when they do not have an HPC cluster ;o)

**Comment by AlbanSagouis** [comment]
> Alban, maybe for your script the challenge will be that you used your latest mobsim version from GiHub, while for other users it will be much more easy to use the CRAN version of mobsim. Does that cause problems? Of course, the best would be to release an updated version on CRAN, but this might include some effort. So from my perspective it would be best if your script just uses the CRAN version. Another option is to add a call to install_github() into 0_init_dirs_load_packages.R so that the latest version is installed. What do you think?

Hi,

I'll test that but the CRAN version of mobsim should work as well. I'm not sure if the simulations would be the same despite the seed being fixed though.

**Comment by AlbanSagouis** [comment]
> 
> Hi @sablowes and @AlbanSagouis,
> 
> I hope I did all necessary changes in "my" main files 0_init_dirs_load_packages.R and 1_analysis_get_biodiv_new.R. Currently R is running and creating the results again and saves them into the intermediate_results folder. I already pushed the first part onto GitHub.
> 
> Do you agree to the adjusted file structure?
> 
> So from my side you can jump into adjusting your files now. Let me know when there are any question.
> 

I made all necessary modifications in my script and 0_init_dirs_load_packages.R. I used the absolute path example you provided.

The community simulation script (7_sim_random_sampling.R) saves intermediate results (huge objects), a figure and final results but I don't provide any them in the folder, is that a problem?

**Comment by sablowes** [comment]
File size matters. Max file size is 100MB - I’ll have to take a look at how big the model fits are to see if we can save them in the intermediate folder. Similarly, if your simulation results are greater than 100MB, then we’ll have to accept that we can’t put them in the repo.

**Comment by sablowes** [comment]
@FelixMay:
- do we want to retain analyses S_std1? I don't think we ever refer to them in the ms, and they are more likely to confuse than anything else.

**Comment by FelixMay** [comment]
Hi @sablowes, thanks for thei hint with S_std1. I will take care of that.

I did not think about the file size issue so far. I guess there are different approaches to take care of this:
1. Only save intermediate results that are really necessary to reproduce the final results
2. Save more aggregated intermediate results than detailed once if possible
3. If 1 and 2 do not work add comments so that readers of the code understand that they have to save stuff to their disk reload it from there.
Does that make sense?

**Comment by FelixMay** [comment]
Hi @AlbanSagouis, I am just running your R script. What is the expected runtime on a decent laptop? Does it make sense to have a look with 2000 replicates or should I lower this number for testing?
With respect to saving data in my understanding it should be possible that readers reproduce Ex_Dat_Fig1.png, right? When I get it right, this requires 3 example communities with 40000 individuals and 9 posterior distributions. This should clearly less than 100 MB.

@Alban and @sablowes: The two scripts to reproduce the Figure are 7_plot_fig_S1.R and 7_sim_random_sampling.R. So if the first one saves too much output that the second one needs is to put the code of both files into one file. Or distribute the code differently to two files so that more aggregated intermediate results (e.g. distributions of parameters instead of simulated data) are save in between. What do you think? Should I take care of this or can one of you guys do that?

cheers,

Felix

**Comment by AlbanSagouis** [comment]
Hi @FelixMay It does take a long time, I recommend a much smaller number of repetition for a test.

The intermediate file is not necessary before running Shane's 7_plot_fig_S1.R script but the result table is. I asked Shane to save the one he used for analyses in FragFrame1/intermediate_results.

**Comment by FelixMay** [comment]
Hi @sablowes and @sablowes, as guidance to our code revision I thought about my idea for the overall goal more precisely. Here it is:

In my opinion, a reader with decent knowledge in R and GitHub should be able to create our result figures and table in a few hours (a working day at maximum). That means all the needed data and code should be there and we should save as little intermediate output as possible to the disk, but as much as needed to keep computation times to a few minutes or hours (and add comments so that readers get an idea, which scripts they can run in decent time and where they rather read data from files).  

So far to the my ideal. Of course, we do not need to fully go there if this is too much work in terms or re-organizing the code and savin stuff to RAM instead of ROM.

Felix

**Comment by FelixMay** [comment]
@AlbanSagouis, sorry for the large number of messages. maybe one phonecall would be more efficient;o)
I did minor changes in the last lines of your script and a test with 200 replicates. Please check that I did not change aynthing important. With 200 replicates the output table is 200 KB, so even times times larger should be no problem at all. What I do not understand is how the coordinates and species labels for the upper panels with Ext_Dat_Fig1 are saved or handed over to Shane's script.

Furthermore, One coding idea: You have two nested four loops in the script and you save the full data of all communities in the RAM. I think a LOT of RAM can be saved by just using one nested for loop and only save the communities that you want to plot later and only the diversity indices are all other communities.

**Comment by sablowes** [comment]
Some of this inefficiency would have been coded due to my wish to have
everything in the case we needed to figure out what was going on ;)

**Comment by AlbanSagouis** [comment]
Hi @FelixMay and @sablowes 
Indeed, the simulation script could be much more efficient but we wanted to save every community in case we wanted to come back to it and compute different biodiversity indices. 

And you are right regarding the plotted communities, saving these coordinates is not in the script so it might not be transparent for users.

**Comment by sablowes** [comment]
@FelixMay is 99_misc_check_missing_values.R needed? Or was that for inspection at some point earlier? And do we use the x_betapart_study_*.csv files for anything?

**Comment by FelixMay** [comment]
Hi @shane, you are right. I just removed the beta_part_study stuff.

One question: I just pulled the repo. There is some stuff in the intermediate_results but nothing in the main results. Is this intended? I will have a quick look at your files over the next days.

**Comment by sablowes** [comment]
I don’t see a folder called results? Only intermediate_results.

**Comment by FelixMay** [comment]
Ups, I created a folder locally, but it seems Git does not track empty folders. I added just a nonsense file there, so now it is on GitHub as well. Sorry

**Comment by sablowes** [comment]
OK. Got it. I will move the model fits to that folder.
Do want to put figures in there too?

**Comment by FelixMay** [comment]
Yes, this was my idea. However, while I think everything should be there, it am open to any useful file structure. I notice that Jon and you are working on the DropBox. Is the preparation of the resubmission still a lot of technical and editorial work or is it OK? Just let me know if and how I can help.

**Comment by sablowes** [comment]
All figures or just main text?

I think Jon has everything he needs for the resubmission now. Not sure where he is up to on the response. And there was a bit of work to do getting the ms down to six pages. But I think he will resubmit today or very soon.

You should take a look at the figures to make sure you think they look ok: I made some changes due to space limitations (both main text and extended data), and we also went black and white for figure 3 and 4 as we could not justify the expense for colour.

**Comment by FelixMay** [comment]
Hi @sablowes, sorry same thing my my extendend_data_figs_tabls folder. It was there locally, but not on GitHub. Now I checked the the file structure is completely synced. Sorry, I was not aware that GutHub does not sync empty folders, but is makes sense ...

**Comment by FelixMay** [comment]
@sablowes Hi Shane, I finally find time to double check our repo. Have you ever heard of byte-order-marks in UTF8? Just learned about this ans luckily managed to remove i form our meta-data file ;o)
Now have a few questions: In the file 3c_fragSize_fit_interaction_models.R there is a save command in the end, which is commented out. If I remember correctly, the interaction models were included in the extended data, right? So I guess, but I am not sure that the output should be save int he corresponding folder in the repo? Is that right, or do I overlook something?
Furthermore, in the the 3d_ files there are quite some save command commented out, but the files are there in main_results. Can you please check, that all the output commands are active if they should be? I also found some slashes missing in your read_csv calls, but this is easy to fix. Thanks and all the best.

**Comment by sablowes** [comment]
I’ll take a look. I think I left those save commands commented out because I got sick of the slow process of pushing the model fits to GitHub with my home internet. But if you want it all there I'll make it happen.

**Comment by FelixMay** [comment]
Hi @sablowes , I make good progress with the repo, but I am not able to reproduce Fig Ex_Dat_Fig1.png. When I run the script "7_plot_fig_S1.R" line 63 throws the following error:

Picking joint bandwidth of NaN
Error in tmp$grobs[[leg]] : 
  attempt to select less than one element in get1index

I could not figure out what the problem is here. Shane, any ideas?

**Comment by FelixMay** [comment]
Hi @AlbanSagouis, in our repo there is a extended_data_figs_tabs\samplingS2000_N40000_mp1.png.
I guess in principle this file should be produced by the script \r_scripts\7_a_sim_random_sampling.R (note that I just changed the file name so that the file order matches the order of execution). But in the current version this figure is not created. Could you adjust the R-script so that it does produce the figure? I note that there is loop in lines 66 - 75 that can create all maps of all communities. I hope it is easy to adjust this code so that onle the needed example is created? 

I know that I am picky with reproduceability, but we are almost there, I think ;o)

**Comment by AlbanSagouis** [comment]
Hi @FelixMay ,
The script wrote to create this figure with the three panels, viridis colours and nice axes was moved around between scripts, I wrote a first version and Shane adapted, but the code was deleted at one point I think. I'm writing something close :)

**Comment by sablowes** [comment]
On my computer, something had changed in the dplyr package, and the nest function was broken meaning the models were not being fit.

It works now for me. But depending on the version of the tidyverse may not work universally.

On the request you sent Alban: I made that plot using a modified version of his code that is long gone. I’ve no plan to rewrite it again.

**Comment by FelixMay** [comment]
@sablowes : Hi shane, I can reproduce Ex_Dat_fig1 know! So your change also works on my machine (I update all packages prior to testing your change) - many thanks!!!

@AlbanSagouis: The great thing is that nothing is lost in Git, onbce it was committed. Sorry for deleting code, but it should be still available in the history. So please do not rewrite code again - or only when this is faster than finding the respective code in the history ;o)
I am happy to search in the commit history for the relevant code! Do you have any hint how the file was called that included the code? Was it part of "sim_random_sampling.R"

**Comment by sablowes** [comment]
that particular piece of code likely never got committed, rather it existed on my machine only…I know, I know. the reproducibility police can get in line after the other authorities who have me in their sights!

**Comment by FelixMay** [comment]
@AlbanSagouis: Alban, obviously you rewrote the code faster than I was even able to write this comment! So everything is there now - many thanks!!! (I might restructure a bit so that readers do not have to uncomment lines to reproduce, but I have all that I need to do this)

best greetings from the reproducibility police!

**Comment by AlbanSagouis** [comment]
I hope it works because I was not able to fully test it on my machine...

**Comment by FelixMay** [comment]
Hi @AlbanSagouis, all fine! I just tested the script with 100 replicates and it worked perfectly now. Thanks for prompt responses!

**Comment by AlbanSagouis** [comment]
Great!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by FelixMay** [comment]
Hi @sablowes, the reproducibility police is back at work with another minor comment:
The script 7_plot_fig_S7_latitude.R creates an Ex_Dat_Fig7 that looks different than the previous one and different from the corresponding tiff version that you just created. I think this can be solved just by adjusting file names. Could you do this so that figure labels in the repo and the paper match?

Furthermore, I deleted comments that said that certain intermediate results were not on GitHub. Now they are there as response to my pickyness, right?

I will finish my checking tomorrow!!!

**Comment by FelixMay** [comment]
Hi @sablowes, thanks again for your prompt reaction. I checked all files now, so these are most likely my last requests. I still found problems in 7_plot_fig_S4_robustCheck.R
1) This file makes use of teh file table_inset.png, but I did not find which file creates this table (I searched for table_inset in all files, but it only showed up in this R-script?)

2) I think it worked before, but when I recreate Ex_Dat_Fig4 again the vertical lines are strange. I tried to fix it by myself, but I did not manage. Do you have any ideas?

I wonder if we should stick to png files on the repo to save a bit of space, but this is something I can change just before archiving. Is the change from png to tiff relared to any news from Nature?

**Comment by sablowes** [comment]
I edit that table ‘by hand’. I added some code to generate the values, but I needed to edit the table in excel and make it into an image etc. for the publication. We can print the table as an image in R, but making the ‘metric’ column something other than simple names (i.e., the expressions we have currently) is tricky (and I’m not wasting any more time figuring out if it is possible).

I added an argument that appears to have gotten lost / changed to the geom_errorbarh() calls. Extended Data Figure 4 looks ok to me now.

Nature requested that all Extended Data Figures were provided as .eps, .tiff or .jpg. I would have preferred eps, but they do not support semi-transparency (or at least, not on my machine) - so I went with tiff. I don’t mind what  you do for GitHub, some got changed yesterday as I was producing them for the Dropbox. But I didn’t change them all as upload speeds from home are v slow.

**Comment by FelixMay** [comment]
Hi @sablowes, this is absolutely fine with the table and thanks for the clarification. But there is still a problem with Ex_Dat_Fig4. When I run the script I get the warning "Ignoring unknown parameters: width" and the Figure still has too lon vertical lines. When you do not have an idea, I will spent (a bit) of time to fix it. I guess it is about package versions. Can you sent your sessionInfo() and which versions of ggplot2 and ggstance do you have? Does the geom_errorbarh() refer to ggplot2 or ggstance?

**Comment by sablowes** [comment]
geom_errorbarh() is from ggplot2 (I think). And yes, it appears to have changed a bit recently. My initial code had a height argument, instead of width. But now, when I use height on my machine, I get the long whiskers on the horizontal error bars (and the warning about ignoring the unknown parameter: height). You could try height = 0 everywhere I have width = 0.


Session info ───────────────────────────────────────────────────────────────────────────────────────────────── setting  value                       
 version  R version 3.5.1 (2018-07-02)
 os       macOS  10.14.1              
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Europe/Berlin               
 date     2020-05-28                  

Packages ───────────────────────────────────────────────────────────────────────────────────────────────── package        * version   date       lib source                              
 abind            1.4-5     2016-07-21 [1] CRAN (R 3.5.0)                      
 ade4             1.7-13    2018-08-31 [1] CRAN (R 3.5.0)                      
 adegenet         2.1.1     2018-02-02 [1] CRAN (R 3.5.0)                      
 adegraphics      1.0-15    2018-12-18 [1] CRAN (R 3.5.0)                      
 adephylo         1.1-11    2017-12-18 [1] CRAN (R 3.5.0)                      
 adespatial     * 0.3-7     2019-06-04 [1] CRAN (R 3.5.2)                      
 ape              5.2       2018-09-24 [1] CRAN (R 3.5.0)                      
 assertthat       0.2.1     2019-03-21 [1] CRAN (R 3.5.2)                      
 backports        1.1.2     2017-12-13 [1] CRAN (R 3.5.0)                      
 base64enc        0.1-3     2015-07-28 [1] CRAN (R 3.5.0)                      
 bayesplot        1.6.0     2018-08-02 [1] CRAN (R 3.5.0)                      
 boot             1.3-20    2017-08-06 [1] CRAN (R 3.5.1)                      
 bridgesampling   0.6-0     2018-10-21 [1] CRAN (R 3.5.0)                      
 brms           * 2.8.0     2019-03-15 [1] CRAN (R 3.5.2)                      
 Brobdingnag      1.2-6     2018-08-13 [1] CRAN (R 3.5.0)                      
 broom            0.5.6     2020-04-20 [1] CRAN (R 3.5.1)                      
 callr            3.1.1     2018-12-21 [1] CRAN (R 3.5.0)                      
 cellranger       1.1.0     2016-07-27 [1] CRAN (R 3.5.0)                      
 cli              2.0.2     2020-02-28 [1] CRAN (R 3.5.2)                      
 cluster          2.0.7-1   2018-04-13 [1] CRAN (R 3.5.1)                      
 coda             0.19-2    2018-10-08 [1] CRAN (R 3.5.0)                      
 colorspace       1.4-0     2019-01-13 [1] CRAN (R 3.5.2)                      
 colourpicker     1.0       2017-09-27 [1] CRAN (R 3.5.0)                      
 cowplot        * 0.9.3     2018-07-15 [1] CRAN (R 3.5.0)                      
 crayon           1.3.4     2017-09-16 [1] CRAN (R 3.5.0)                      
 crosstalk        1.0.0     2016-12-21 [1] CRAN (R 3.5.0)                      
 data.table       1.12.0    2019-01-13 [1] CRAN (R 3.5.2)                      
 DBI              1.0.0     2018-05-02 [1] CRAN (R 3.5.0)                      
 dbplyr           1.4.3     2020-04-19 [1] CRAN (R 3.5.1)                      
 deldir           0.1-15    2018-04-01 [1] CRAN (R 3.5.0)                      
 desc             1.2.0     2018-05-01 [1] CRAN (R 3.5.0)                      
 devtools       * 2.0.1     2018-10-26 [1] CRAN (R 3.5.1)                      
 digest           0.6.18    2018-10-10 [1] CRAN (R 3.5.0)                      
 dplyr          * 0.8.5     2020-03-07 [1] CRAN (R 3.5.2)                      
 DT               0.5       2018-11-05 [1] CRAN (R 3.5.0)                      
 dygraphs         1.1.1.6   2018-07-11 [1] CRAN (R 3.5.0)                      
 ellipsis         0.3.0     2019-09-20 [1] CRAN (R 3.5.2)                      
 expm             0.999-3   2018-09-22 [1] CRAN (R 3.5.0)                      
 fansi            0.4.0     2018-10-05 [1] CRAN (R 3.5.0)                      
 forcats        * 0.5.0     2020-03-01 [1] CRAN (R 3.5.2)                      
 fs               1.2.6     2018-08-23 [1] CRAN (R 3.5.0)                      
 gdata            2.18.0    2017-06-06 [1] CRAN (R 3.5.0)                      
 generics         0.0.2     2018-11-29 [1] CRAN (R 3.5.0)                      
 ggplot2        * 3.3.0     2020-03-05 [1] CRAN (R 3.5.2)                      
 ggridges       * 0.5.1     2018-09-27 [1] CRAN (R 3.5.0)                      
 ggstance       * 0.3.1     2018-07-20 [1] CRAN (R 3.5.0)                      
 glue             1.3.1     2019-03-12 [1] CRAN (R 3.5.2)                      
 gmodels          2.18.1    2018-06-25 [1] CRAN (R 3.5.0)                      
 gridExtra        2.3       2017-09-09 [1] CRAN (R 3.5.0)                      
 gridGraphics   * 0.5-0     2020-02-25 [1] CRAN (R 3.5.2)                      
 gtable           0.2.0     2016-02-26 [1] CRAN (R 3.5.0)                      
 gtools           3.8.1     2018-06-26 [1] CRAN (R 3.5.0)                      
 haven            2.2.0     2019-11-08 [1] CRAN (R 3.5.2)                      
 hms              0.5.3     2020-01-08 [1] CRAN (R 3.5.2)                      
 htmltools        0.3.6     2017-04-28 [1] CRAN (R 3.5.0)                      
 htmlwidgets      1.3       2018-09-30 [1] CRAN (R 3.5.0)                      
 httpuv           1.4.5.1   2018-12-18 [1] CRAN (R 3.5.0)                      
 httr             1.4.1     2019-08-05 [1] CRAN (R 3.5.2)                      
 igraph           1.2.2     2018-07-27 [1] CRAN (R 3.5.0)                      
 iNEXT          * 2.0.17    2018-09-19 [1] CRAN (R 3.5.0)                      
 inline           0.3.15    2018-05-18 [1] CRAN (R 3.5.0)                      
 jsonlite         1.6       2018-12-07 [1] CRAN (R 3.5.0)                      
 KernSmooth       2.23-15   2015-06-29 [1] CRAN (R 3.5.1)                      
 labeling         0.3       2014-08-23 [1] CRAN (R 3.5.0)                      
 later            0.7.5     2018-09-18 [1] CRAN (R 3.5.0)                      
 lattice          0.20-35   2017-03-25 [1] CRAN (R 3.5.1)                      
 latticeExtra     0.6-28    2016-02-09 [1] CRAN (R 3.5.0)                      
 lazyeval         0.2.1     2017-10-29 [1] CRAN (R 3.5.0)                      
 LearnBayes       2.15.1    2018-03-18 [1] CRAN (R 3.5.0)                      
 lifecycle        0.2.0     2020-03-06 [1] CRAN (R 3.5.2)                      
 loo              2.1.0     2019-03-13 [1] CRAN (R 3.5.2)                      
 lubridate        1.7.4     2018-04-11 [1] CRAN (R 3.5.0)                      
 magick         * 2.0       2018-10-05 [1] CRAN (R 3.5.0)                      
 magrittr         1.5       2014-11-22 [1] CRAN (R 3.5.0)                      
 maps           * 3.3.0     2018-04-03 [1] CRAN (R 3.5.0)                      
 markdown         0.9       2018-12-07 [1] CRAN (R 3.5.0)                      
 MASS             7.3-50    2018-04-30 [1] CRAN (R 3.5.1)                      
 Matrix           1.2-14    2018-04-13 [1] CRAN (R 3.5.1)                      
 matrixStats      0.54.0    2018-07-23 [1] CRAN (R 3.5.0)                      
 memoise          1.1.0     2017-04-21 [1] CRAN (R 3.5.0)                      
 mgcv             1.8-24    2018-06-23 [1] CRAN (R 3.5.1)                      
 mime             0.6       2018-10-05 [1] CRAN (R 3.5.0)                      
 miniUI           0.1.1.1   2018-05-18 [1] CRAN (R 3.5.0)                      
 mobr           * 1.0       2018-11-19 [1] Github (MoBiodiv/mobr@2e942c1)      
 mobsim         * 0.1.0     2017-11-02 [1] CRAN (R 3.5.0)                      
 modelr           0.1.6     2020-02-22 [1] CRAN (R 3.5.2)                      
 munsell          0.5.0     2018-06-12 [1] CRAN (R 3.5.0)                      
 mvtnorm          1.0-8     2018-05-31 [1] CRAN (R 3.5.0)                      
 nlme             3.1-137   2018-04-07 [1] CRAN (R 3.5.1)                      
 pbapply        * 1.3-4     2018-01-10 [1] CRAN (R 3.5.0)                      
 permute          0.9-4     2016-09-09 [1] CRAN (R 3.5.0)                      
 phylobase        0.8.4     2017-04-21 [1] CRAN (R 3.5.0)                      
 pillar           1.4.3     2019-12-20 [1] CRAN (R 3.5.2)                      
 pkgbuild         1.0.2     2018-10-16 [1] CRAN (R 3.5.0)                      
 pkgconfig        2.0.2     2018-08-16 [1] CRAN (R 3.5.0)                      
 pkgload          1.0.2     2018-10-29 [1] CRAN (R 3.5.0)                      
 plyr             1.8.4     2016-06-08 [1] CRAN (R 3.5.0)                      
 pracma         * 2.1.8     2018-10-16 [1] CRAN (R 3.5.0)                      
 prettyunits      1.0.2     2015-07-13 [1] CRAN (R 3.5.0)                      
 processx         3.2.1     2018-12-05 [1] CRAN (R 3.5.0)                      
 progress         1.2.0     2018-06-14 [1] CRAN (R 3.5.0)                      
 promises         1.0.1     2018-04-13 [1] CRAN (R 3.5.0)                      
 ps               1.3.0     2018-12-21 [1] CRAN (R 3.5.0)                      
 purrr          * 0.3.4     2020-04-17 [1] CRAN (R 3.5.1)                      
 R6               2.4.0     2019-02-14 [1] CRAN (R 3.5.2)                      
 RColorBrewer     1.1-2     2014-12-07 [1] CRAN (R 3.5.0)                      
 Rcpp           * 1.0.1     2019-03-17 [1] CRAN (R 3.5.2)                      
 readr          * 1.3.1     2018-12-21 [1] CRAN (R 3.5.0)                      
 readxl           1.3.1     2019-03-13 [1] CRAN (R 3.5.2)                      
 remotes          2.0.2     2018-10-30 [1] CRAN (R 3.5.0)                      
 reprex           0.3.0     2019-05-16 [1] CRAN (R 3.5.2)                      
 reshape2         1.4.3     2017-12-11 [1] CRAN (R 3.5.0)                      
 rlang            0.4.5     2020-03-01 [1] CRAN (R 3.5.2)                      
 rncl             0.8.3     2018-07-27 [1] CRAN (R 3.5.0)                      
 RNeXML           2.2.0     2018-11-01 [1] CRAN (R 3.5.0)                      
 rprojroot        1.3-2     2018-01-03 [1] CRAN (R 3.5.0)                      
 rsconnect        0.8.11    2018-11-12 [1] CRAN (R 3.5.0)                      
 rstan            2.18.2    2018-11-07 [1] CRAN (R 3.5.0)                      
 rstantools       1.5.1     2018-08-22 [1] CRAN (R 3.5.0)                      
 rstudioapi       0.11      2020-02-07 [1] CRAN (R 3.5.2)                      
 rvest            0.3.5     2019-11-08 [1] CRAN (R 3.5.2)                      
 scales         * 1.0.0     2018-08-09 [1] CRAN (R 3.5.0)                      
 seqinr           3.4-5     2017-08-01 [1] CRAN (R 3.5.0)                      
 sessioninfo      1.1.1     2018-11-05 [1] CRAN (R 3.5.0)                      
 shiny            1.2.0     2018-11-02 [1] CRAN (R 3.5.0)                      
 shinyjs          1.0       2018-01-08 [1] CRAN (R 3.5.0)                      
 shinystan        2.5.0     2018-05-01 [1] CRAN (R 3.5.0)                      
 shinythemes      1.1.2     2018-11-06 [1] CRAN (R 3.5.0)                      
 sp               1.3-1     2018-06-05 [1] CRAN (R 3.5.0)                      
 spData           0.2.9.4   2018-09-15 [1] CRAN (R 3.5.0)                      
 spDataLarge      0.3.1     2020-03-18 [1] Github (Nowosad/spDataLarge@1f52612)
 spdep            0.7-9     2018-09-28 [1] CRAN (R 3.5.0)                      
 StanHeaders      2.18.0    2018-10-07 [1] CRAN (R 3.5.0)                      
 stringi          1.2.4     2018-07-20 [1] CRAN (R 3.5.0)                      
 stringr        * 1.4.0     2019-02-10 [1] CRAN (R 3.5.2)                      
 testthat         2.0.1     2018-10-13 [1] CRAN (R 3.5.0)                      
 threejs          0.3.1     2017-08-13 [1] CRAN (R 3.5.0)                      
 tibble         * 3.0.1     2020-04-20 [1] CRAN (R 3.5.1)                      
 tidyr          * 1.0.2     2020-01-24 [1] CRAN (R 3.5.2)                      
 tidyselect       0.2.5     2018-10-11 [1] CRAN (R 3.5.0)                      
 tidyverse      * 1.3.0     2019-11-21 [1] CRAN (R 3.5.2)                      
 usethis        * 1.4.0     2018-08-14 [1] CRAN (R 3.5.0)                      
 utf8             1.1.4     2018-05-24 [1] CRAN (R 3.5.0)                      
 uuid             0.1-2     2015-07-28 [1] CRAN (R 3.5.0)                      
 vctrs            0.2.4     2020-03-10 [1] CRAN (R 3.5.2)                      
 vegan            2.5-3     2018-10-25 [1] CRAN (R 3.5.0)                      
 viridisLite    * 0.3.0     2018-02-01 [1] CRAN (R 3.5.0)                      
 withr            2.1.2     2018-03-15 [1] CRAN (R 3.5.0)                      
 XML              3.98-1.20 2019-06-06 [1] CRAN (R 3.5.2)                      
 xml2             1.3.2     2020-04-23 [1] CRAN (R 3.5.1)                      
 xtable           1.8-3     2018-08-29 [1] CRAN (R 3.5.0)                      
 xts              0.11-2    2018-11-05 [1] CRAN (R 3.5.0)                      
 yaml             2.2.0     2018-07-25 [1] CRAN (R 3.5.0)                      
 zoo              1.8-4     2018-09-19 [1] CRAN (R 3.5.0)

**Comment by FelixMay** [comment]
Hi @sablowes, you found the same solutions as I did in the same time ;o)
However, there are geom_errorh functions in two packages and as we do not want to have small lines at the end of the lines in this case geom_linerange seemed to be safer and more consistent. Everything fixed now!!!
